### ISSUE TITLE
Support launching in Terminal

### ISSUE THREAD

**Issue by jdek** [renard/emacs-build-macosx#3]
If you symlink `/Applications/Emacs.app/Contents/MacOS/Emacs` to `/usr/local/bin/emacs` and launch with `emacs -nw` then it doesn't find the lib/libexec/etc folders.

To begin testing this I ripped out your 'site-lisp' and 'patches' functionality temporarily:
```
$ emacs -nw
Warning: arch-dependent data dir '/Users/user/Desktop/emacs-build-macosx/build/nextstep/Emacs.app/Contents/MacOS/libexec/': No such file or directory
Warning: arch-independent data dir '/Users/user/Desktop/emacs-build-macosx/build/nextstep/Emacs.app/Contents/Resources/etc/': No such file or directory
Warning: Lisp directory '/Users/user/Desktop/emacs-build-macosx/build/nextstep/Emacs.app/Contents/Resources/lisp': No such file or directory
Error: /Users/user/Desktop/emacs-build-macosx/build/nextstep/Emacs.app/Contents/Resources/etc/charsets: No such file or directory
Emacs will not function correctly without the character map files.
Please check your installation!
```

This location seems to be baked into the binary. I think a simple way might be to find where it's being defined and just replace it with `/Applications/Emacs.app` but this doesn't solve the cases where someone might have the application elsewhere.
```
[pwd was /Applications/Emacs.app]
$ grep -R '/Users/user/Desktop/emacs-build-macosx/build/nextstep/Emacs.app' .
Binary file ./Contents/MacOS/Emacs.pdmp matches
Binary file ./Contents/MacOS/Emacs matches
```

Any thoughts would be appreciated.

**Comment by jdek** [comment]
A launcher like (`/usr/local/bin/emacs`) would work too, though it would be nice to not have the user's build directory baked into the build too:
```
#!/bin/sh
/Applications/Emacs.app/Contents/MacOS/Emacs "$@"
```

**Comment by renard** [comment]
I checked with Emacs For Mac OSX (from which this tool was inspired) and it turns out it has the exact same problem.
I don't really know why some files are hardcoded that way.

Your workaround can do the job. And I would just enhance the way it work in 2 different directions:

Find the application itself using  `osascript`:
```
osascript -e 'POSIX path of (path to application "Emacs")'
```
The drawback is that you have to allow the terminal to access to `Emacs.app`

The other way is to look for the `Emacs.app` in Applications folders which are :
* `/Applications`
* `~/Applications`

I am not sure any other folder is suitable for applications location.

That said I prefer the second solution which is less invasive. 

If you want to to provide a patch I will merge it otherwise I will integrate it when I find some time this week or next week.

**Comment by jdek** [comment]
osascript solution requires user to click permission prompt, I think just adding an example script in the README and leaving it up to the user is best. My solution to avoid user infomation in the build is just to build from /tmp directory.

**Comment by jdek** [comment]
Great, thanks! Looks good. 👍
